version: "3.8"

services:
    web:
        build: ./
        command: gunicorn bookCommunity.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - staticfiles:/home/app/web/staticfiles
            - uploadsfiles:/home/app/web/uploadsfiles
            - database:/home/app/web/database
        expose:
            - 8000
        environment:
            - ALLOWED_HOSTS
            - DEBUG
            - SECRET_KEY
            - MAP_BOX_API
        # restart: always
    nginx:
        build: ./nginx
        volumes:
            - staticfiles:/home/app/web/staticfiles
            - uploadsfiles:/home/app/web/uploadsfiles
        depends_on:
            - web
        # restart: always
volumes:
    staticfiles:
        external: true
    uploadsfiles:
        external: true
    database:
        external: true