version: "3.8"

services:
    web:
        build: ./
        command: gunicorn bookCommunity.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - /root/bookCafePersistentStorage/staticfiles:/home/app/web/staticfiles
            - /root/bookCafePersistentStorage/uploadsfiles:/home/app/web/uploadsfiles
            - /root/bookCafePersistentStorage/database:/home/app/web/database
        expose:
            - 8000
        env_file:
            - ./.env
        restart: always
    nginx:
        build: ./nginx
        volumes:
            - /root/bookCafePersistentStorage/staticfiles:/home/app/web/staticfiles
            - /root/bookCafePersistentStorage/uploadsfiles:/home/app/web/uploadsfiles
        depends_on:
            - web
        hostname: cafe-book-nginx
        restart: always
